# Generated by Django 4.1 on 2022-09-02 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('author_id', models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffboard',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author_id', models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Freeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author_id', models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freeboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'freeboard',
            },
        ),
    ]
